// <auto-generated />
namespace HardwareShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modify2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify2));
        
        string IMigrationMetadata.Id
        {
            get { return "202406081101489_modify2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
