// <auto-generated />
namespace HardwareShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ModificareCerere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificareCerere));
        
        string IMigrationMetadata.Id
        {
            get { return "202504211003128_ModificareCerere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
